module.exports = {
  plugins: ['prettier-plugin-tailwindcss', 'prettier-plugin-organize-imports'],
  singleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  useTabs: false,
  tabWidth: 2,
  printWidth: 120,
  jsxBracketSameLine: false,
  arrowParens: 'always',
  rangeStart: 0,
  rangeEnd: Infinity,
  htmlWhitespaceSensitivity: 'css',
  proseWrap: 'preserve',
  semi: false,
  jsxSingleQuote: false,
};
