import type { Metadata, Viewport } from "next"
import { cn } from "@/lib/utils"
import "./globals.css"
import { fontMono, fontSans } from "@/lib"
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs"
import Navbar from "@/components/Navbar/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "w-full overflow-x-hidden h-svh font-sans antialiased",
            fontSans.variable,
            fontMono.variable,
          )}
        >
          <SignedOut>
            <div className="flex h-screen min-h-screen flex-col items-center justify-between">
              {children}
            </div>
          </SignedOut>
          <SignedIn>
            <div className="container mx-auto flex h-screen min-h-screen flex-col items-center">
            <div className="w-full max-w-[1024px] space-y-8">
              <Navbar />
              {children}</div>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
