import type { Metadata, Viewport } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { fontMono, fontSans } from "@/lib";
import { ClerkProvider, SignInButton, SignedIn, SignedOut } from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
	maximumScale: 1,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={cn("w-full overflow-x-hidden h-svh font-sans antialiased", fontSans.variable, fontMono.variable)}>
					<SignedOut>
						<div className="flex h-screen min-h-screen flex-col items-center justify-between overflow-x-hidden">{children}</div>
					</SignedOut>
					<SignedIn>
						<div className="flex min-h-screen">{children}</div>
					</SignedIn>
				</body>
			</html>
		</ClerkProvider>
	);
}
